### ISSUE TITLE
Overlapping polymerase error

### ISSUE THREAD

**Issue by alexismhill3** [clauswilke/pinetree#11]
When running Pinetree on a mutant T7 genome, this error occurs:

Traceback (most recent call last):
  File "phage_mutant_model.py", line 265, in <module>
    main()
  File "phage_mutant_model.py", line 261, in main
    sim.simulate(time_limit=1500, time_step=5, output="phage_counts.tsv")
RuntimeError: Polymerase __ribosome (start: 8323, stop: 8352, index: 11) is overlapping polymerase __ribosome (start: 8347, stop: 8376, index: 12) by more than one position on polymer __rna

The mutant T7 has a modified gene around coordinates 1200-2000, which shouldn't affect ribosome binding around coordinates 8323-8376.

Python environment used:
Python 3.7.5
biopython==1.76
cmake==3.17.2
numpy==1.18.5
pinetree==0.2.0

**Comment by alexismhill3** [comment]
Mutant phage pinetree script and genbank file to replicate error:
[phage_mutant_model.zip](https://github.com/clauswilke/pinetree/files/4881351/phage_mutant_model.zip)

**Comment by jeffreybarrick** [comment]
We decided the error seems to be something about having overlapping genes. It's true the documentation say that you can't use overlapping genes or even overlapping RBSs.

https://pinetree.readthedocs.io/en/latest/python_ref.html#pinetree.Genome.add_gene

However, for the T7 example, it **_successfully_** loads and runs a model that has overlapping genes?

https://github.com/clauswilke/pinetree/blob/master/examples/phage_model.py

This is a dump of the gene start-end that it is loading at this line to create the model
```
phage.add_gene(name=name, start=start, stop=stop, rbs_start=start - 30, rbs_stop=start, rbs_strength=1e7)
```

Several genes overlap, such as gene 5.9 and gene 6, gene 1.1 and gene 1.2, etc. unless I'm missing something?

```
gene 0.3  (positions  891 - 1468 )
protein_kinase-0.7  (positions  1469 - 3138 )
rnapol-1  (positions  3139 - 5887 )
gene 1.2  (positions  5888 - 6448 )
gene 1.1  (positions  6007 - 6135 )
gene 1.3  (positions  6449 - 7588 )
gene 1.4  (positions  7608 - 7763 )
gene 1.5  (positions  7791 - 7880 )
gene 1.6  (positions  7906 - 8166 )
gene 1.7  (positions  8166 - 8756 )
gene 1.8  (positions  8749 - 8895 )
gp-2  (positions  8898 - 9092 )
gene 2.5  (positions  9158 - 9856 )
gene 2.8  (positions  9857 - 10276 )
gene 3  (positions  10257 - 10706 )
lysozyme-3.5  (positions  10706 - 11161 )
gene 3.8  (positions  11225 - 11590 )
gene 4A  (positions  11565 - 13265 )
gene 4.2  (positions  12988 - 13326 )
gene 4.3  (positions  13352 - 13564 )
gene 4.5  (positions  13584 - 13853 )
gene 4.7  (positions  13927 - 14334 )
gene 5  (positions  14353 - 16467 )
gene 5.3  (positions  16483 - 16839 )
gene 5.5  (positions  16851 - 17150 )
gene 5.7  (positions  17150 - 17359 )
gene 5.9  (positions  17359 - 17517 )
gene 6  (positions  17504 - 18406 )
gene 6.3  (positions  18394 - 18507 )
gene 6.5  (positions  18605 - 18859 )
gene 6.7  (positions  18864 - 19130 )
gene 7  (positions  19130 - 19531 )
gene 7.3  (positions  19535 - 19834 )
gene 7.7  (positions  19848 - 20240 )
gene 8  (positions  20240 - 21850 )
gene 9  (positions  21950 - 22873 )
gene 10A  (positions  22967 - 24004 )
gene 11  (positions  24228 - 24818 )
gene 12  (positions  24842 - 27226 )
gene 13  (positions  27307 - 27723 )
gene 14  (positions  27728 - 28318 )
gene 15  (positions  28325 - 30568 )
gene 16  (positions  30595 - 34551 )
gene 17  (positions  34624 - 36285 )
gene 17.5  (positions  36344 - 36547 )
gene 18  (positions  36553 - 36822 )
gene 18.5  (positions  36917 - 37348 )
gene 18.7  (positions  37032 - 37283 )
gene 19  (positions  37370 - 39130 )
gene 19.2  (positions  38016 - 38273 )
gene 19.3  (positions  38553 - 38726 )
gene 19.5  (positions  39389 - 39538 )
```

**Comment by clauswilke** [comment]
I suspect overlapping genes are necessary but not sufficient to cause the crash. I'd also argue that a crash is always bad. Pinetree should either accept the input genome and run without crash or reject the input genome as containing features that aren't supported. Since overlapping genes are common in bacteriophages, it would be best if we could identify the cause of the undefined behavior and fix it.

**Comment by alexismhill3** [comment]
I agree. I'm going to mark this as resolved, and then link it to a new issue that addresses this more generally.
