### ISSUE TITLE
Pinetree should be able to handle overlapping genes

### ISSUE THREAD

**Issue by alexismhill3** [clauswilke/pinetree#12]
The documentation states that Pinetree doesn't support overlapping genes or genes that overlap with a ribosome binding site. Confusingly, if the user does try to add overlapping genes to the simulation, Pinetree will run anyway; this sometimes (but not always; see #11) results in a seemingly unrelated error.

Given that overlapping genes are quite abundant in real phage genomes, it would be best to fix this undefined behavior and implement full support for overlapping genes.

**Comment by croots** [comment]
This issue appears to occur in the example `phage_model.py` and the supplied wildtype genome if you use other randomness seeds, such as seed 45, with the default ignored genes.

`RuntimeError: Polymerase __ribosome (start: 7762, stop: 7791, index: 9) is overlapping polymerase __ribosome (start: 7787, stop: 7816, index: 10) by more than one position on polymer __rna
`
