### ISSUE TITLE
Unable to install pinetree 

### ISSUE THREAD

**Issue by g-krik** [clauswilke/pinetree#21]
Hi there -

I have been trying to install pinetree on an M2 MacBook and have installed all dependencies listed, however have been met with various error codes, the latest being "ERROR: Could not build wheels for pinetree which use PEP 517 and cannot be installed directly." I have tried numerous fixes suggested on online forums which have been unsuccessful, I was wondering if you had encountered this problem before or have any suggestions? 

Thanks,
Gil

**Comment by clauswilke** [comment]
Please provide a detailed log of what commands you enter and what the output is. Thanks!

**Comment by g-krik** [comment]
As suggested I have attempted to install pinetree using Python 3.8.10 with the following packages installed:
cmake version 3.25.0
pip version 22.3.1
setuptools version 65.6.3
wheel version 0.38.4

I have attached the error code that I receive upon running the command 'pip3 install pinetree'. 

[GK Pinetree Installation Error Code 09:12:22.odt](https://github.com/clauswilke/pinetree/files/10196622/GK.Pinetree.Installation.Error.Code.09.12.22.odt)

I hope this will help to make the issue clearer! Thank you!

**Comment by clauswilke** [comment]
Please paste your log here in a comment so we can read it.
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by g-krik** [comment]
gilkrikler@dhcp-10-248-107-91 ~ % pip3 install pinetree
Collecting pinetree
  Using cached pinetree-0.3.0.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pinetree
  Building wheel for pinetree (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pinetree (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [230 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11-universal2-cpython-38
      creating build/lib.macosx-11-universal2-cpython-38/pinetree
      copying src/pinetree/averager.py -> build/lib.macosx-11-universal2-cpython-38/pinetree
      copying src/pinetree/batch.py -> build/lib.macosx-11-universal2-cpython-38/pinetree
      copying src/pinetree/__init__.py -> build/lib.macosx-11-universal2-cpython-38/pinetree
      running build_ext
      -- The C compiler identification is AppleClang 14.0.0.14000029
      -- The CXX compiler identification is AppleClang 14.0.0.14000029
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 (found version "3.8.10")
      -- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib
      -- pybind11 v2.3.dev0
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- LTO enabled
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/build/temp.macosx-11-universal2-cpython-38
      [ 10%] Building CXX object CMakeFiles/core.dir/src/pinetree/feature.cpp.o
      [ 10%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/feature.cpp.o
      [ 15%] Building CXX object CMakeFiles/core.dir/src/pinetree/polymer.cpp.o
      [ 21%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/polymer.cpp.o
      [ 26%] Building CXX object CMakeFiles/core.dir/src/pinetree/choices.cpp.o
      [ 31%] Building CXX object CMakeFiles/core.dir/src/pinetree/tracker.cpp.o
      [ 36%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/choices.cpp.o
      [ 42%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/tracker.cpp.o
      [ 47%] Building CXX object CMakeFiles/core.dir/src/pinetree/model.cpp.o
      [ 52%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/model.cpp.o
      [ 57%] Building CXX object CMakeFiles/core.dir/src/pinetree/gillespie.cpp.o
      [ 63%] Building CXX object CMakeFiles/core.dir/src/pinetree/reaction.cpp.o
      [ 68%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/gillespie.cpp.o
      [ 73%] Building CXX object CMakeFiles/core.dir/src/pinetree/python_bindings.cpp.o
      [ 78%] Building CXX object CMakeFiles/pinetree_test.dir/src/pinetree/reaction.cpp.o
      [ 84%] Building CXX object CMakeFiles/pinetree_test.dir/tests/test_main.cpp.o
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:20:3: note: in instantiation of function template specialization 'pybind11::class_<BindingSite, std::shared_ptr<BindingSite>>::class_<char[144]>' requested here
        py::class_<BindingSite, std::shared_ptr<BindingSite>>(m, "BindingSite",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:40:3: note: in instantiation of function template specialization 'pybind11::class_<ReleaseSite, std::shared_ptr<ReleaseSite>>::class_<char[122]>' requested here
        py::class_<ReleaseSite, std::shared_ptr<ReleaseSite>>(m, "ReleaseSite",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:60:3: note: in instantiation of function template specialization 'pybind11::class_<Polymerase, std::shared_ptr<Polymerase>>::class_<char[130]>' requested here
        py::class_<Polymerase, std::shared_ptr<Polymerase>>(m, "Polymerase",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:83:3: note: in instantiation of function template specialization 'pybind11::class_<Mask, std::shared_ptr<Mask>>::class_<char[140]>' requested here
        py::class_<Mask, std::shared_ptr<Mask>>(m, "Mask",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:104:3: note: in instantiation of function template specialization 'pybind11::class_<Rnase, std::shared_ptr<Rnase>>::class_<char[147]>' requested here
        py::class_<Rnase, std::shared_ptr<Rnase>>(m, "Rnase",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:125:3: note: in instantiation of function template specialization 'pybind11::class_<SpeciesReaction, std::shared_ptr<SpeciesReaction>>::class_<char[164]>' requested here
        py::class_<SpeciesReaction, std::shared_ptr<SpeciesReaction>>(
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:146:3: note: in instantiation of function template specialization 'pybind11::class_<MobileElementManager, std::shared_ptr<MobileElementManager>>::class_<char[119]>' requested here
        py::class_<MobileElementManager, std::shared_ptr<MobileElementManager>>(
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:169:3: note: in instantiation of function template specialization 'pybind11::class_<Model, std::shared_ptr<Model>>::class_<char[365]>' requested here
        py::class_<Model, std::shared_ptr<Model>>(m, "Model",
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:308:3: note: in instantiation of function template specialization 'pybind11::class_<Polymer, std::shared_ptr<Polymer>>::class_<>' requested here
        py::class_<Polymer, Polymer::Ptr>(m, "Polymer");
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:309:3: note: in instantiation of function template specialization 'pybind11::class_<Genome, Polymer, std::shared_ptr<Genome>>::class_<>' requested here
        py::class_<Genome, Polymer, Genome::Ptr>(m, "Genome")
        ^
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:1:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/pybind11.h:1077:9: warning: expression result unused [-Wunused-value]
              PYBIND11_EXPAND_SIDE_EFFECTS(add_base<options>(record));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/lib/pybind11/include/pybind11/detail/common.h:651:47: note: expanded from macro 'PYBIND11_EXPAND_SIDE_EFFECTS'
      #define PYBIND11_EXPAND_SIDE_EFFECTS(PATTERN) pybind11::detail::expand_side_effects{ ((PATTERN), void(), false)..., false }
                                                    ^                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/src/pinetree/python_bindings.cpp:431:3: note: in instantiation of function template specialization 'pybind11::class_<Transcript, Polymer, std::shared_ptr<Transcript>>::class_<>' requested here
        py::class_<Transcript, Polymer, Transcript::Ptr>(m, "Transcript")
        ^
      11 warnings generated.
      [ 89%] Linking CXX shared module /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/build/lib.macosx-11-universal2-cpython-38/pinetree/core.cpython-38-darwin.so
      ld: warning: -undefined dynamic_lookup may not work with chained fixups
      [ 89%] Built target core
      [ 94%] Building CXX object CMakeFiles/pinetree_test.dir/tests/unit_tests.cpp.o
      In file included from /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/tests/test_main.cpp:2:
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/tests/./lib/catch.hpp:7937:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
                  CATCH_BREAK_INTO_DEBUGGER();
                  ^
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/tests/./lib/catch.hpp:7651:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
          #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                                    ^
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/tests/./lib/catch.hpp:7630:34: note: expanded from macro 'CATCH_TRAP'
          #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                       ^
      <inline asm>:1:2: note: instantiated into assembly here
              int $3
              ^
      1 error generated.
      make[2]: *** [CMakeFiles/pinetree_test.dir/tests/test_main.cpp.o] Error 1
      make[1]: *** [CMakeFiles/pinetree_test.dir/all] Error 2
      make: *** [all] Error 2
      /private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 107, in <module>
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-build-env-he9__npk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 41, in run
        File "<string>", line 72, in build_extension
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pinetree
Failed to build pinetree
ERROR: Could not build wheels for pinetree, which is required to install pyproject.toml-based projects
gilkrikler@dhcp-10-248-107-91 ~ %

**Comment by g-krik** [comment]
Here is the error log as a comment, apologies if the file I linked to in the previous comment wasn't opening for you.

**Comment by clauswilke** [comment]
@alexismhill3 Looks like a problem with the catch library to me. Maybe it needs to be updated to the latest version?

```
/private/var/folders/kz/116l6lrd4fz7zww670sclr4m0000gn/T/pip-install-mfnob6r8/pinetree_dd080a0cd52f4bd982eab5ea1680d254/tests/./lib/catch.hpp:7937:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
CATCH_BREAK_INTO_DEBUGGER();
```

@g-krik It is inappropriate provide an error log as an .odt file. At a minimum, it is a security risk. Getting people to open random binary files is a classical attack vector. It's also impolite. You expect me to download a file, install software to open the file, and then run the software just so I can read the error message that you could have just as well copied into a comment.
